# Generated by Django 3.1.5 on 2021-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('discount', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
