# Generated by Django 3.1.5 on 2021-06-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh', '0002_insta_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insta_images',
            old_name='link',
            new_name='href',
        ),
    ]
