# Generated by Django 3.1.5 on 2021-04-20 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, null=True)),
                ('temp', models.FloatField(max_length=5)),
                ('feels_like', models.FloatField(max_length=5)),
                ('pressure', models.FloatField(max_length=4)),
                ('humidity', models.FloatField(max_length=3)),
                ('wind_dir', models.IntegerField()),
                ('wind_speed', models.FloatField(max_length=5)),
                ('datetime_added', models.DateTimeField(default=datetime.datetime(2021, 4, 20, 16, 41, 45, 257397))),
            ],
        ),
    ]
