# Generated by Django 3.1.5 on 2021-04-20 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 16, 44, 4, 824133, tzinfo=utc)),
        ),
    ]
