# Generated by Django 3.1.5 on 2021-06-08 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('country', models.CharField(default='India', max_length=300)),
                ('city', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='images/profile_images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
